#pragma once

enum ePacketType
{
	CS_PT_LOGIN = 1,
	CS_PT_INFIELD,
	CS_PT_DUMMY,
	CS_PT_NOWPOSITION,
	CS_PT_MOVEUSER,
	CS_PT_ARRIVE,
	CS_PT_LOGOUT,
	CS_PT_MOVESECTOR,
	CS_PT_INSECTOR,
	CS_PT_OUTSECTOR,
	CS_PT_NEWSECTORUSER
};