#pragma once

enum ePacketType
{
	CS_PT_LOGIN = 1,
	CS_PT_INFIELD,
	CS_PT_DUMMY,
	CS_PT_NEWUSERENTRY,
	CS_PT_MOVEUSER,
	CS_PT_ARRIVE,
	CS_PT_LOGOUT,
	CS_PT_MOVESECTOR,
	CS_PT_INSECTOR,
	CS_PT_OUTSECTOR,
	CS_PT_NEWSECTORUSER,
	CS_PT_SENDSECTOR_NEWUSERENTRY = 19,
	CS_PT_MOVE_MONSTER,
	CS_PT_CREATE_MONSTER,
	CS_PT_EXIT_SECTOR_MONSTER,
	CS_PT_ENTER_SECTOR_MONSTER
};