#pragma once

#define SECTOR_RIGHT 1
#define SECTOR_LEFT -1
#define SECTOR_TOP 32
#define SECTOR_BOTTOM -32
#define SECTOR_LEFT_TOP 31
#define SECTOR_RIGHT_TOP 33
#define SECTOR_LEFT_BOTTOM -33
#define SECTOR_RIGHT_BOTTOM -31